-- =================================================================================
-- 011_fix_rls_all.sql
-- Fixes RLS policies for 4 broken features and creates the missing Events table.
-- =================================================================================

-- 1. CUSTOMER ENQUIRIES (contact_messages)
-- Allow public and authenticated users to submit contact forms.
DROP POLICY IF EXISTS "contact_messages: public insert" ON public.contact_messages;
CREATE POLICY "contact_messages: public insert" 
ON public.contact_messages 
FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- 2. NOTIFY ME (notify_me_requests)
-- Allow public and authenticated users to submit back-in-stock requests.
DROP POLICY IF EXISTS "notify_me: public insert" ON public.notify_me_requests;
CREATE POLICY "notify_me: public insert" 
ON public.notify_me_requests 
FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- 3. HOMEPAGE BANNERS
-- Allow public to read enabled banners for the homepage carousel.
DROP POLICY IF EXISTS "homepage_banners: public read" ON public.homepage_banners;
CREATE POLICY "homepage_banners: public read" 
ON public.homepage_banners 
FOR SELECT 
TO anon, authenticated 
USING (is_enabled = true);

-- Allow admin (authenticated) full access to banners.
DROP POLICY IF EXISTS "homepage_banners: admin read" ON public.homepage_banners;
CREATE POLICY "homepage_banners: admin read" 
ON public.homepage_banners 
FOR SELECT 
TO authenticated 
USING (true);

DROP POLICY IF EXISTS "homepage_banners: admin insert" ON public.homepage_banners;
CREATE POLICY "homepage_banners: admin insert" 
ON public.homepage_banners 
FOR INSERT 
TO authenticated 
WITH CHECK (true);

DROP POLICY IF EXISTS "homepage_banners: admin update" ON public.homepage_banners;
CREATE POLICY "homepage_banners: admin update" 
ON public.homepage_banners 
FOR UPDATE 
TO authenticated 
USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "homepage_banners: admin delete" ON public.homepage_banners;
CREATE POLICY "homepage_banners: admin delete" 
ON public.homepage_banners 
FOR DELETE 
TO authenticated 
USING (true);

-- 4. COUPONS
-- Allow public to read active coupons for frontend checkout validation.
-- (Secure validation is done server-side in createRazorpayOrder)
DROP POLICY IF EXISTS "coupons: public read" ON public.coupons;
CREATE POLICY "coupons: public read" 
ON public.coupons 
FOR SELECT 
TO anon, authenticated 
USING (is_active = true);

-- Allow public to insert coupon usage after checkout
DROP POLICY IF EXISTS "coupon_usage: public insert" ON public.coupon_usage;
CREATE POLICY "coupon_usage: public insert" 
ON public.coupon_usage 
FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- Allow public to increment coupon usage_count (update)
DROP POLICY IF EXISTS "coupons: public update used_count" ON public.coupons;
CREATE POLICY "coupons: public update used_count" 
ON public.coupons 
FOR UPDATE 
TO anon, authenticated 
USING (is_active = true) 
WITH CHECK (true);


-- 5. EVENTS
-- Create the missing events table
CREATE TABLE IF NOT EXISTS public.events (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title               TEXT NOT NULL,
  event_type          TEXT DEFAULT 'Conference',
  short_description   TEXT,
  description         TEXT,
  date                DATE,
  time                TEXT,
  location            TEXT,
  city                TEXT,
  registration_url    TEXT,
  banner_image_url    TEXT,
  is_active           BOOLEAN DEFAULT true,
  is_featured         BOOLEAN DEFAULT false,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS on events
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

-- Allow public to read active events
DROP POLICY IF EXISTS "events: public read" ON public.events;
CREATE POLICY "events: public read" 
ON public.events 
FOR SELECT 
TO anon, authenticated 
USING (is_active = true);

-- Allow admin full access to events
DROP POLICY IF EXISTS "events: admin all" ON public.events;
CREATE POLICY "events: admin all" 
ON public.events 
FOR ALL 
TO authenticated 
USING (true) WITH CHECK (true);
